### ISSUE TITLE
Documentation on how you got it working with Home Assistant?

### ISSUE THREAD

**Issue by onedr0p** [Supermortal/python-tuya-oittm#7]
That would be awesome...

**Comment by Supermortal** [comment]
I haven't used it with Home Assistant yet, only directly with my device. I had/have plans to use this to build an implementation in HA, but unfortunately, my humidifier is spotty about when it wants to listen to commands. I'll get around to building it when I have some time.

**Comment by onedr0p** [comment]
> but unfortunately, my humidifier is spotty about when it wants to listen to commands

I've noticed the same thing when using the Tuya app or IFTTT... maybe it is a flaw in the device itself :(

**Comment by codeclinic** [comment]
Is this a direct(ish) replacement for the Clach04 package? Does it support PIR & Door sensors by any chance?

**Comment by Supermortal** [comment]
It was supposed to be, kind of. I just built it for fun. The code is extendable, so those could be supported, but they're not now. I think the original Node implementation has moved onto another, less hacky authentication solution as well, so it would need updating all around.

**Comment by codeclinic** [comment]
Oh it's looking like we need someone to pick up this again if tuya can move forward in terms of Home Assistant.

**Comment by onedr0p** [comment]
Project appears dead, closing.
